### ISSUE TITLE
Cannot read property 'stage' of undefined

### ISSUE THREAD

**Issue by jaakkotuosa** [serverless-components/aws-iam-policy#2]
Hi!
I am not sure if the project is still alive, but just in case:

I tried to use the component like this:
```
name: [retracted]

environment:
  component: ./serverless-components/serverless-env
  inputs:
    env: ${env.STAGE}

apiRouteLambdaPolicy:
  component: "@serverless/aws-iam-policy"
  inputs:
    name: api-route-lambda-policy-${env.STAGE}
    description: AWS IAM Policy for API route lambda
    policy:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"
        - Effect: Allow
          Action:
            - ssm:Describe*
            - ssm:Get*
          Resource: arn:aws:ssm:eu-west-1:[retracted]:parameter/[retracted]/*
```

AWS_PROFILE=[retracted] STAGE=[retracted] serverless --debug fails with:
  ```
error:
  TypeError: Cannot read property 'stage' of undefined
    at new Component (/Users/tuosaja/.serverless/components/registry/npm/@serverless/aws-iam-policy@0.0.1/node_modules/@serverless/components/src/lib/component/serverless.js:18:34)
    at new AwsIamPolicy (/Users/tuosaja/.serverless/components/registry/npm/@serverless/aws-iam-policy@0.0.1/node_modules/@serverless/aws-iam-policy/serverless.js:11:1)
    at Template.load (/snapshot/serverless/node_modules/@serverless/core/src/Component.js:113:36)
    at fn (/snapshot/serverless/node_modules/@serverless/template/utils.js:309:27)
    at async Promise.all (index 0)
    at syncState (/snapshot/serverless/node_modules/@serverless/template/utils.js:333:3)
    at Template.default (/snapshot/serverless/node_modules/@serverless/template/serverless.js:63:5)
    at Object.runComponents (/snapshot/serverless/node_modules/@serverless/cli/src/index.js:211:17)

  1s › Template › TypeError: Cannot read property 'stage' of undefined
```

That's pretty early in file aws-iam-policy/serverless.js, is the code compatible with current Serverless components?
